Traceback (most recent call last):
  File "/home/oslab/Desktop/seda/lib/infer_inclusion.py", line 108, in <module>
    main()
  File "/home/oslab/Desktop/seda/lib/infer_inclusion.py", line 104, in main
    infer(contexts, list(all_deleted)[0], False)
  File "/home/oslab/Desktop/seda/lib/infer_inclusion.py", line 76, in infer
    max_count = max(counts.values())
ValueError: max() arg is an empty sequence
